services:
  pgdatabase:
    image: postgres:13
    environment:
      - POSTGRES_USER=${user}
      - POSTGRES_PASSWORD=${password}
      - POSTGRES_DB=${db}

      
    volumes:
      - "./ny_taxi_postgres_data:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    volumes:
      - ./data_pgadmin:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${pgadmin_default_email}
      - PGADMIN_DEFAULT_PASSWORD=${pgadmin_default_password}
    ports:
      - "8080:80"
    